# config.yaml
crawler:
  base_pdf_path: "{HOME}/github/swalakshya/cataloguesearch-configs"
  base_text_path: "{HOME}/cataloguesearch/text"
  base_ocr_path: "{HOME}/cataloguesearch/ocr"
  sqlite_db_path: "{HOME}/cataloguesearch/db/cataloguesearch.db"
  bookmark_extractor_llm: "ollama"
  ocr_engine: "tesseract"
  tessdata_dir: "{BASE_DIR}/tessdata"
  default_llm_model: "gemini-2.5-flash"
  secondary_llm_model: "gemini-3-flash-preview"
  llm_workers: 10

index:
  opensearch_config: "{BASE_DIR}/configs/opensearch-config.yaml"
  chunking_algos:
    default:
      chunk_size: 500
      chunk_overlap: 50
    dynamic:
      similarity_threshold: 0.5
  chunk_strategy: "advanced"

search:
  filtered_metadata_fields: ["Granth_date_ranges", "Pravachan", "Name", "Anuyog", "Author"]
  active_categories: ["Pravachan", "Granth"]

opensearch:
  host: "{OPENSEARCH_HOST}"
  port: "{OPENSEARCH_PORT}"
  index_name: cataloguesearch_prod
  metadata_index_name: cataloguesearch_prod_metadata

vector_embeddings:
  embedding_model: BAAI/bge-m3
  reranking_model: BAAI/bge-reranker-base
  # Path to the optimized ONNX model directory inside the container.
  # If this path exists, the application will use the faster ONNX model.
  reranker_onnx_path: "{BASE_DIR}/models/bge-reranker-base-onnx"
  # Supported types: base, fp16, quantized_8bit
  embedding_model_type: fp16

transliteration:
  api_url: "http://localhost:8500"
  default_language: "hi"
  default_topk: 5
  timeout: 10  # seconds
