"""
End-to-end integration tests for LLMIndexGenerator via Discovery.

Alpha : flat — all 13 pages indexed as a single document
Beta  : sub-sectioned — pages 1-7  as Beta Sec A,
                        pages 8-13 as Beta Sec B

Both documents are indexed through Discovery.crawl() so that discovery.py is
fully exercised: config loading, sub-section routing, state management, etc.

All tests use real OpenSearch (dry_run=False).
API tests are decorated @pytest.mark.integration and spin up a live API server
on port 19877.
"""

import os
import shutil
import tempfile
import threading
import time

import fitz
import pytest
import requests

from backend.common.opensearch import create_indices_if_not_exists, get_opensearch_client
from backend.config import Config
from backend.crawler.discovery import Discovery
from backend.crawler.index_generator import IndexGenerator
from backend.crawler.index_state import IndexState
from backend.search.index_searcher import IndexSearcher
from tests.backend.base import *   # brings in module-scoped autouse `initialise` fixture
from tests.backend.common import write_config_file

# ── paths ─────────────────────────────────────────────────────────────────────
_DATA_DIR  = os.path.join(os.path.dirname(__file__), "../data/granth")
_ALPHA_DIR = os.path.join(_DATA_DIR, "alpha")
_BETA_DIR  = os.path.join(_DATA_DIR, "beta")

# ── sub-section names (must match scan_config.json written by `indexed`) ──────
_BETA_SEC_FIELD  = "Name"
_BETA_SEC_A_NAME = "Beta Sec A"
_BETA_SEC_B_NAME = "Beta Sec B"

# ── doc IDs discovered from the index after crawling (set by `indexed`) ───────
_ALPHA_DOC_ID  = None
_BETA_A_DOC_ID = None
_BETA_B_DOC_ID = None


def _raw_query(opensearch_client, index_name, query, size=500):
    """Execute a raw OpenSearch query; return the list of hits."""
    response = opensearch_client.search(
        index=index_name,
        body={"size": size, "query": query},
    )
    return response["hits"]["hits"]


def _docs_for(opensearch_client, index_name, doc_id):
    """All indexed chunks for a given document_id."""
    return _raw_query(
        opensearch_client, index_name,
        {"term": {"document_id": doc_id}},
    )


def _verse_chunks_for(opensearch_client, index_name, doc_id):
    """Chunks that have a verse_type field (verse-indexed)."""
    return _raw_query(opensearch_client, index_name, {
        "bool": {
            "must": [
                {"term":   {"document_id": doc_id}},
                {"exists": {"field": "verse_type"}},
            ]
        }
    })


def _para_chunks_for(opensearch_client, index_name, doc_id):
    """Chunks that have a vector_embedding field (paragraph-indexed)."""
    return _raw_query(opensearch_client, index_name, {
        "bool": {
            "must": [
                {"term":   {"document_id": doc_id}},
                {"exists": {"field": "vector_embedding"}},
            ]
        }
    })


# ── module-scoped fixtures ────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def config(initialise):
    return Config()


@pytest.fixture(scope="module")
def opensearch_client(config):
    return get_opensearch_client(config)


@pytest.fixture(scope="module")
def indexed(config, opensearch_client):
    """
    Index alpha (flat) and beta (sub-sectioned) via Discovery.crawl().

    Temp layout (mirrors the real production layout):
        <base>/data/pdfs/
            alpha.pdf            (13 blank pages — needed by get_scan_config)
            beta.pdf             (13 blank pages)
            scan_config.json     (ocr_engine=llm, ignore_bookmarks, sub_sections for beta)
            config.json          (language=hi, category=Granth)
            alpha_config.json    (Granth=Alpha Granth)
            beta_config.json     (Granth=Beta Granth)
        <base>/data/ocr/
            alpha/page_0001.json … page_0013.json   (copied from tests/data)
            beta/page_0001.json  … page_0013.json
        <base>/data/texts/
        <base>/crawl_state.db

    config.settings()["crawler"] paths are updated so Discovery uses the temp
    dirs, then restored on teardown.

    Doc IDs are auto-generated by SingleFileProcessor; after crawling they are
    discovered from the index and stored in module globals so all test
    assertions can reference them without knowing the UUID values.

    Starts from a clean slate (all three indices deleted + recreated) and
    ends in a clean slate (all three indices deleted on teardown).
    """
    global _ALPHA_DOC_ID, _BETA_A_DOC_ID, _BETA_B_DOC_ID

    all_indices = [
        config.OPENSEARCH_INDEX_NAME,
        config.OPENSEARCH_METADATA_INDEX_NAME,
    ]

    # ── clean slate ───────────────────────────────────────────────────────────
    for idx in all_indices:
        opensearch_client.indices.delete(index=idx, ignore=[400, 404])
    create_indices_if_not_exists(config, opensearch_client)

    # ── temp directory layout ─────────────────────────────────────────────────
    base_dir = tempfile.mkdtemp(prefix="granth_e2e_")
    pdf_dir  = os.path.join(base_dir, "data", "pdfs")
    ocr_dir  = os.path.join(base_dir, "data", "ocr")
    text_dir = os.path.join(base_dir, "data", "texts")
    db_path  = os.path.join(base_dir, "crawl_state.db")

    os.makedirs(pdf_dir)
    os.makedirs(os.path.join(ocr_dir, "alpha"))
    os.makedirs(os.path.join(ocr_dir, "beta"))
    os.makedirs(text_dir)

    # ── create minimal PDFs (get_scan_config calls fitz.open) ────────────────
    for name in ("alpha", "beta"):
        doc = fitz.open()
        for _ in range(13):
            doc.new_page()
        doc.save(os.path.join(pdf_dir, f"{name}.pdf"))
        doc.close()

    # ── copy pre-built OCR data into the expected locations ───────────────────
    for name, src_dir in (("alpha", _ALPHA_DIR), ("beta", _BETA_DIR)):
        dst_dir = os.path.join(ocr_dir, name)
        for fname in os.listdir(src_dir):
            if fname.startswith("page_") and fname.endswith(".json"):
                shutil.copy(os.path.join(src_dir, fname), os.path.join(dst_dir, fname))

    # ── write scan_config.json ────────────────────────────────────────────────
    write_config_file(os.path.join(pdf_dir, "scan_config.json"), {
        "default": {
            "chunk_strategy":   "llm",
            "ocr_engine":       "llm",
            "ignore_bookmarks": True,
            "stop_words":       ["विशेष"],
            "question_prefix":  ["प्रश्न"],
            "answer_prefix":    ["उत्तर"],
            "verses":           ["hindi_verse", "prakrit_verse", "sanskrit_verse"],
            "typo_list":        [],
        },
        "alpha": {
            "start_page": 1,
            "end_page":   13,
        },
        "beta": {
            "sub_sections": [
                {"field": _BETA_SEC_FIELD, "name": _BETA_SEC_A_NAME,
                 "start_page": 1, "end_page": 7},
                {"field": _BETA_SEC_FIELD, "name": _BETA_SEC_B_NAME,
                 "start_page": 8, "end_page": 13},
            ],
        },
    })

    # ── write config.json and per-file *_config.json ──────────────────────────
    write_config_file(os.path.join(pdf_dir, "config.json"),
                      {"language": "hi", "category": "Granth"})
    write_config_file(os.path.join(pdf_dir, "alpha_config.json"),
                      {"Name": "Alpha Granth"})
    write_config_file(os.path.join(pdf_dir, "beta_config.json"),
                      {"Name": "Beta Granth"})

    # ── point config to the temp dirs (same as common.setup()) ───────────────
    crawler = config.settings()["crawler"]
    orig = {k: crawler[k] for k in
            ("base_pdf_path", "base_text_path", "base_ocr_path", "sqlite_db_path")}
    crawler["base_pdf_path"]  = pdf_dir
    crawler["base_text_path"] = text_dir
    crawler["base_ocr_path"]  = ocr_dir
    crawler["sqlite_db_path"] = db_path

    try:
        discovery = Discovery(
            config,
            IndexGenerator(config, opensearch_client),
            IndexState(config.SQLITE_DB_PATH),
        )
        # process=False because OCR files are already pre-populated
        discovery.crawl(process=False, index=True)

        opensearch_client.indices.refresh(index=config.OPENSEARCH_INDEX_NAME)

        # ── discover doc IDs from the index (no hardcoding needed) ───────────
        all_hits = opensearch_client.search(
            index=config.OPENSEARCH_INDEX_NAME,
            body={"size": 500, "query": {"match_all": {}}},
        )["hits"]["hits"]

        for hit in all_hits:
            meta = hit["_source"].get("metadata", {})
            doc_id = hit["_source"]["document_id"]
            sub = meta.get("sub_section") or {}
            if meta.get("Name") == "Alpha Granth":
                _ALPHA_DOC_ID = doc_id
            elif sub.get("name") == _BETA_SEC_A_NAME:
                _BETA_A_DOC_ID = doc_id
            elif sub.get("name") == _BETA_SEC_B_NAME:
                _BETA_B_DOC_ID = doc_id

        yield {}

    finally:
        # ── restore config paths ──────────────────────────────────────────────
        crawler.update(orig)
        shutil.rmtree(base_dir, ignore_errors=True)
        for idx in all_indices:
            opensearch_client.indices.delete(index=idx, ignore=[400, 404])


@pytest.fixture(scope="module")
def searcher(config):
    return IndexSearcher(config)


# ═════════════════════════════════════════════════════════════════════════════
# Alpha — paragraph chunks
# ═════════════════════════════════════════════════════════════════════════════

class TestAlphaParagraphIndexing:
    """Flat-indexed alpha document — paragraph chunk assertions."""

    @pytest.fixture(scope="class")
    def alpha_para(self, indexed, config, opensearch_client):
        return _para_chunks_for(opensearch_client, config.OPENSEARCH_INDEX_NAME, _ALPHA_DOC_ID)

    def test_paragraphs_are_indexed(self, alpha_para):
        assert len(alpha_para) > 0

    def test_all_have_correct_document_id(self, alpha_para):
        for doc in alpha_para:
            assert doc["_source"]["document_id"] == _ALPHA_DOC_ID

    def test_all_have_granth_category(self, alpha_para):
        for doc in alpha_para:
            assert doc["_source"]["metadata"]["category"] == "Granth"

    def test_all_have_vector_embedding(self, alpha_para):
        for doc in alpha_para:
            src = doc["_source"]
            assert "vector_embedding" in src
            assert isinstance(src["vector_embedding"], list)
            assert len(src["vector_embedding"]) > 0

    def test_cross_page_paragraph_found_by_search(self, indexed, searcher):
        """Overflow text merged across pages 1-2 is searchable as one paragraph."""
        results, total = searcher.perform_granth_search(
            "पानी हवा और धूप", exact_match=True, exclude_words=[],
            categories={}, detected_language="hi", page_size=10, page_number=1,
        )
        assert total > 0
        # document_id in results is the chunk_id which starts with the doc_id
        assert any(r["document_id"].startswith(_ALPHA_DOC_ID) for r in results)

    def test_granth_search_results_all_have_granth_category(self, indexed, searcher):
        """perform_granth_search applies category=Granth filter; no stray docs returned."""
        results, _ = searcher.perform_granth_search(
            "पानी हवा और धूप", exact_match=False, exclude_words=[],
            categories={}, detected_language="hi", page_size=20, page_number=1,
        )
        for r in results:
            assert r["metadata"].get("category") == "Granth"

    def test_pravachan_search_finds_nothing(self, indexed, searcher):
        """No Pravachan-categorised docs are indexed; pravachan search must return 0."""
        _, total = searcher.perform_pravachan_search(
            "पानी हवा और धूप", exact_match=False, exclude_words=[],
            categories={}, detected_language="hi", page_size=10, page_number=1,
        )
        assert total == 0


# ═════════════════════════════════════════════════════════════════════════════
# Alpha — verse chunks
# ═════════════════════════════════════════════════════════════════════════════

class TestAlphaVerseIndexing:
    """Verse chunks for the flat-indexed alpha document."""

    @pytest.fixture(scope="class")
    def alpha_verse(self, indexed, config, opensearch_client):
        return _verse_chunks_for(opensearch_client, config.OPENSEARCH_INDEX_NAME, _ALPHA_DOC_ID)

    def test_verse_chunks_are_indexed(self, alpha_verse):
        assert len(alpha_verse) > 0

    def test_all_have_verse_type_field(self, alpha_verse):
        allowed = {"hindi_verse", "prakrit_verse", "sanskrit_verse"}
        for doc in alpha_verse:
            assert doc["_source"]["verse_type"] in allowed

    def test_all_have_correct_document_id(self, alpha_verse):
        for doc in alpha_verse:
            assert doc["_source"]["document_id"] == _ALPHA_DOC_ID

    def test_all_have_granth_category(self, alpha_verse):
        for doc in alpha_verse:
            assert doc["_source"]["metadata"]["category"] == "Granth"

    def test_all_three_verse_types_present(self, alpha_verse):
        """Page 12 carries all three types; the full set must appear in the index."""
        types = {doc["_source"]["verse_type"] for doc in alpha_verse}
        assert types == {"hindi_verse", "prakrit_verse", "sanskrit_verse"}

    def test_hindi_verse_text_indexed(self, indexed, config, opensearch_client):
        """जल है तो कल है (page 7 hindi_verse) is found in a verse chunk."""
        hits = _raw_query(opensearch_client, config.OPENSEARCH_INDEX_NAME, {
            "bool": {
                "must": [
                    {"term":  {"document_id": _ALPHA_DOC_ID}},
                    {"match": {"text_content_hindi": "जल है तो कल है"}},
                ]
            }
        })
        assert len(hits) > 0
        assert hits[0]["_source"]["verse_type"] == "hindi_verse"

    def test_prakrit_verse_text_indexed(self, indexed, config, opensearch_client):
        """गामे वा जइ अरण्णे वा (page 5 prakrit_verse) is found in a verse chunk."""
        hits = _raw_query(opensearch_client, config.OPENSEARCH_INDEX_NAME, {
            "bool": {
                "must": [
                    {"term":  {"document_id": _ALPHA_DOC_ID}},
                    {"match": {"text_content_hindi": "गामे वा जइ अरण्णे वा"}},
                ]
            }
        })
        assert len(hits) > 0
        assert hits[0]["_source"]["verse_type"] == "prakrit_verse"

    def test_sanskrit_verse_text_indexed(self, indexed, config, opensearch_client):
        """सर्वे भवन्तु सुखिनः (page 6 sanskrit_verse) is found in a verse chunk."""
        hits = _raw_query(opensearch_client, config.OPENSEARCH_INDEX_NAME, {
            "bool": {
                "must": [
                    {"term":  {"document_id": _ALPHA_DOC_ID}},
                    {"match": {"text_content_hindi": "सर्वे भवन्तु सुखिनः"}},
                ]
            }
        })
        assert len(hits) > 0
        assert hits[0]["_source"]["verse_type"] == "sanskrit_verse"


# ═════════════════════════════════════════════════════════════════════════════
# Embedding stripping
# ═════════════════════════════════════════════════════════════════════════════

class TestEmbeddingStripping:
    """verse_type and vector_embedding are mutually exclusive on every chunk."""

    def test_no_verse_chunk_has_embedding(self, indexed, config, opensearch_client):
        verses = _verse_chunks_for(opensearch_client, config.OPENSEARCH_INDEX_NAME, _ALPHA_DOC_ID)
        assert len(verses) > 0
        for doc in verses:
            assert "vector_embedding" not in doc["_source"], (
                f"Verse chunk {doc['_id']} must not carry vector_embedding"
            )

    def test_all_para_chunks_have_embedding(self, indexed, config, opensearch_client):
        paras = _para_chunks_for(opensearch_client, config.OPENSEARCH_INDEX_NAME, _ALPHA_DOC_ID)
        assert len(paras) > 0
        for doc in paras:
            src = doc["_source"]
            assert "vector_embedding" in src
            assert isinstance(src["vector_embedding"], list)
            assert len(src["vector_embedding"]) > 0

    def test_no_chunk_has_both_verse_type_and_embedding(self, indexed, config, opensearch_client):
        """Structural invariant: verse_type and vector_embedding never coexist."""
        hits = _raw_query(opensearch_client, config.OPENSEARCH_INDEX_NAME, {
            "bool": {
                "must": [
                    {"exists": {"field": "verse_type"}},
                    {"exists": {"field": "vector_embedding"}},
                ]
            }
        })
        assert len(hits) == 0, (
            f"{len(hits)} chunk(s) illegally carry both verse_type and vector_embedding"
        )

    def test_para_plus_verse_equals_total(self, indexed, config, opensearch_client):
        """Paragraph count + verse count = total chunk count (no overlap, no gap)."""
        index_name = config.OPENSEARCH_INDEX_NAME
        all_docs   = _docs_for(opensearch_client, index_name, _ALPHA_DOC_ID)
        para_docs  = _para_chunks_for(opensearch_client, index_name, _ALPHA_DOC_ID)
        verse_docs = _verse_chunks_for(opensearch_client, index_name, _ALPHA_DOC_ID)
        assert len(para_docs) + len(verse_docs) == len(all_docs)


# ═════════════════════════════════════════════════════════════════════════════
# Beta — sub-section isolation
# ═════════════════════════════════════════════════════════════════════════════

class TestBetaSubSectionIndexing:
    """Beta indexed in two sub-sections; each has its own document_id."""

    @pytest.fixture(scope="class")
    def sec_a_all(self, indexed, config, opensearch_client):
        return _docs_for(opensearch_client, config.OPENSEARCH_INDEX_NAME, _BETA_A_DOC_ID)

    @pytest.fixture(scope="class")
    def sec_b_all(self, indexed, config, opensearch_client):
        return _docs_for(opensearch_client, config.OPENSEARCH_INDEX_NAME, _BETA_B_DOC_ID)

    def test_sec_a_is_indexed(self, sec_a_all):
        assert len(sec_a_all) > 0

    def test_sec_b_is_indexed(self, sec_b_all):
        assert len(sec_b_all) > 0

    def test_sec_a_document_ids_correct(self, sec_a_all):
        for doc in sec_a_all:
            assert doc["_source"]["document_id"] == _BETA_A_DOC_ID

    def test_sec_b_document_ids_correct(self, sec_b_all):
        for doc in sec_b_all:
            assert doc["_source"]["document_id"] == _BETA_B_DOC_ID

    def test_sec_a_page_numbers_within_range(self, sec_a_all):
        for doc in sec_a_all:
            assert doc["_source"]["page_number"] in range(1, 8)

    def test_sec_b_page_numbers_within_range(self, sec_b_all):
        for doc in sec_b_all:
            assert doc["_source"]["page_number"] in range(8, 14)

    def test_sec_a_verse_pages_absent_from_sec_b(self, indexed, config, opensearch_client):
        """Verse pages 5, 6, 7 (sec A) must not appear under the sec_b document_id."""
        verse_b = _verse_chunks_for(opensearch_client, config.OPENSEARCH_INDEX_NAME, _BETA_B_DOC_ID)
        for doc in verse_b:
            assert doc["_source"]["page_number"] not in {5, 6, 7}

    def test_sec_b_verse_page_absent_from_sec_a(self, indexed, config, opensearch_client):
        """Verse page 12 (sec B) must not appear under the sec_a document_id."""
        verse_a = _verse_chunks_for(opensearch_client, config.OPENSEARCH_INDEX_NAME, _BETA_A_DOC_ID)
        for doc in verse_a:
            assert doc["_source"]["page_number"] != 12

    def test_sec_a_has_verse_pages_5_6_7(self, indexed, config, opensearch_client):
        verse_a = _verse_chunks_for(opensearch_client, config.OPENSEARCH_INDEX_NAME, _BETA_A_DOC_ID)
        verse_pages = {doc["_source"]["page_number"] for doc in verse_a}
        assert {5, 6, 7}.issubset(verse_pages)

    def test_sec_b_has_verse_page_12(self, indexed, config, opensearch_client):
        verse_b = _verse_chunks_for(opensearch_client, config.OPENSEARCH_INDEX_NAME, _BETA_B_DOC_ID)
        verse_pages = {doc["_source"]["page_number"] for doc in verse_b}
        assert 12 in verse_pages

    def test_sec_a_overflow_text_searchable(self, indexed, searcher):
        """बादलों का अध्ययन (pages 1-2 overflow) is in sec_a, not sec_b."""
        results, total = searcher.perform_granth_search(
            "बादलों का अध्ययन", exact_match=True, exclude_words=[],
            categories={}, detected_language="hi", page_size=10, page_number=1,
        )
        assert total > 0
        # document_id in results is the chunk_id which starts with the doc_id
        assert any(r["document_id"].startswith(_BETA_A_DOC_ID) for r in results)
        assert not any(r["document_id"].startswith(_BETA_B_DOC_ID) for r in results)

    def test_sec_b_content_searchable(self, indexed, searcher):
        """प्रकाश की गति (page 8) is in sec_b, not sec_a."""
        results, total = searcher.perform_granth_search(
            "प्रकाश की गति", exact_match=True, exclude_words=[],
            categories={}, detected_language="hi", page_size=10, page_number=1,
        )
        assert total > 0
        # document_id in results is the chunk_id which starts with the doc_id
        assert any(r["document_id"].startswith(_BETA_B_DOC_ID) for r in results)
        assert not any(r["document_id"].startswith(_BETA_A_DOC_ID) for r in results)


# ═════════════════════════════════════════════════════════════════════════════
# Verse search results — no vector_embedding
# ═════════════════════════════════════════════════════════════════════════════

class TestVerseSearchResults:
    """
    Lexical search hits on verse chunks must carry no vector_embedding.
    Lexical search hits on paragraph chunks must carry a vector_embedding.
    """

    def test_verse_hit_has_no_embedding(self, indexed, config, opensearch_client):
        """Searching for hindi_verse text returns chunk(s) without vector_embedding."""
        hits = _raw_query(opensearch_client, config.OPENSEARCH_INDEX_NAME, {
            "bool": {
                "must": [
                    {"term":  {"document_id": _ALPHA_DOC_ID}},
                    {"match": {"text_content_hindi": "जल है तो कल है"}},
                ]
            }
        })
        assert len(hits) > 0, "Expected at least one hit for the hindi_verse phrase"
        for h in hits:
            assert "vector_embedding" not in h["_source"], (
                f"Verse chunk {h['_id']} must not have vector_embedding"
            )

    def test_prakrit_verse_hit_has_no_embedding(self, indexed, config, opensearch_client):
        """Searching for prakrit_verse text returns chunk(s) without vector_embedding."""
        hits = _raw_query(opensearch_client, config.OPENSEARCH_INDEX_NAME, {
            "bool": {
                "must": [
                    {"term":  {"document_id": _ALPHA_DOC_ID}},
                    {"match": {"text_content_hindi": "गामे वा जइ अरण्णे वा"}},
                ]
            }
        })
        assert len(hits) > 0
        for h in hits:
            assert "vector_embedding" not in h["_source"]

    def test_paragraph_hit_has_embedding(self, indexed, config, opensearch_client):
        """Searching for a paragraph-only phrase returns chunk(s) with vector_embedding."""
        hits = _raw_query(opensearch_client, config.OPENSEARCH_INDEX_NAME, {
            "bool": {
                "must": [
                    {"term":  {"document_id": _ALPHA_DOC_ID}},
                    {"match": {"text_content_hindi": "पानी हवा और धूप"}},
                ],
                "must_not": [
                    {"exists": {"field": "verse_type"}},
                ],
            }
        })
        assert len(hits) > 0, "Expected at least one hit for the paragraph phrase"
        for h in hits:
            assert "vector_embedding" in h["_source"], (
                f"Paragraph chunk {h['_id']} must have vector_embedding"
            )

    def test_verse_lexical_search_via_granth_search(self, indexed, searcher):
        """perform_granth_search returns verse text via lexical path."""
        results, total = searcher.perform_granth_search(
            "जल है तो कल है", exact_match=True, exclude_words=[],
            categories={}, detected_language="hi", page_size=10, page_number=1,
        )
        assert total > 0
        # document_id in results is the chunk_id which starts with the doc_id
        assert any(r["document_id"].startswith(_ALPHA_DOC_ID) for r in results)


# ═════════════════════════════════════════════════════════════════════════════
# API integration tests
# ═════════════════════════════════════════════════════════════════════════════

_API_HOST = "127.0.0.1"
_API_PORT = 19877


def _run_api_server(host, port):
    """Target function for the API server daemon thread."""
    import os as _os
    from dotenv import load_dotenv as _load_dotenv
    from backend.config import Config as _Config

    project_root = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
    _load_dotenv(dotenv_path=f"{project_root}/.env", verbose=True)

    test_base_dir = _os.getenv("TEST_BASE_DIR")
    _os.environ["LOGS_DIR"] = "logs"
    _os.environ["CONFIG_PATH"] = f"{test_base_dir}/data/configs/test_config.yaml"
    _Config.reset()

    import sys as _sys
    _sys.modules.pop("backend.api.search_api", None)
    from backend.api.search_api import app
    from uvicorn import Config as UvicornConfig
    import uvicorn
    import asyncio

    cfg = UvicornConfig(app=app, host=host, port=port, log_level="error", access_log=False)
    server = uvicorn.Server(cfg)

    try:
        asyncio.run(server.serve())
    except Exception:
        pass


@pytest.fixture(scope="module")
def api_server(indexed):
    """Start the API server in a daemon thread; tear it down after the module."""
    thread = threading.Thread(
        target=_run_api_server,
        args=(_API_HOST, _API_PORT),
        daemon=True,
    )
    thread.start()

    base_url = f"http://{_API_HOST}:{_API_PORT}"
    deadline = time.time() + 30
    while time.time() < deadline:
        try:
            r = requests.get(f"{base_url}/api/metadata", timeout=1)
            if r.status_code in (200, 404, 500):
                break
        except requests.exceptions.RequestException:
            pass
        time.sleep(0.5)
    else:
        raise TimeoutError("API server did not start within 30 s")

    yield base_url


def _granth_payload(query, exact_match=False, granth_enabled=True):
    return {
        "query": query,
        "language": "hi",
        "exact_match": exact_match,
        "exclude_words": [],
        "categories": {},
        "search_types": {
            "Pravachan": {"enabled": False, "page_size": 10, "page_number": 1},
            "Granth":    {"enabled": granth_enabled, "page_size": 10, "page_number": 1},
        },
        "enable_reranking": False,
    }


class TestGranthSearchAPI:
    """HTTP API integration tests — require the live API server fixture."""

    def test_server_is_up(self, api_server):
        r = requests.get(f"{api_server}/api/metadata")
        assert r.status_code == 200

    def test_response_schema_is_correct(self, api_server):
        r = requests.post(
            f"{api_server}/api/search",
            json=_granth_payload("पानी हवा और धूप"),
        )
        assert r.status_code == 200
        data = r.json()
        for key in ("pravachan_results", "granth_results"):
            assert key in data
            for subkey in ("results", "total_hits", "page_size", "page_number"):
                assert subkey in data[key], f"Missing {subkey} in {key}"

    def test_granth_enabled_returns_results(self, api_server):
        r = requests.post(
            f"{api_server}/api/search",
            json=_granth_payload("पानी हवा और धूप", exact_match=True),
        )
        assert r.status_code == 200
        data = r.json()
        assert data["granth_results"]["total_hits"] > 0

    def test_granth_disabled_returns_zero(self, api_server):
        r = requests.post(
            f"{api_server}/api/search",
            json=_granth_payload("पानी हवा और धूप", granth_enabled=False),
        )
        assert r.status_code == 200
        data = r.json()
        assert data["granth_results"]["total_hits"] == 0

    def test_verse_text_found_via_api(self, api_server):
        """Hindi verse text is returned by lexical granth search."""
        r = requests.post(
            f"{api_server}/api/search",
            json=_granth_payload("जल है तो कल है", exact_match=True),
        )
        assert r.status_code == 200
        data = r.json()
        assert data["granth_results"]["total_hits"] > 0

    def test_beta_sec_a_content_via_api(self, api_server):
        """Pages 1-2 overflow text (sec_a) is findable via the API."""
        r = requests.post(
            f"{api_server}/api/search",
            json=_granth_payload("बादलों का अध्ययन", exact_match=True),
        )
        assert r.status_code == 200
        data = r.json()
        assert data["granth_results"]["total_hits"] > 0

    def test_beta_sec_b_content_via_api(self, api_server):
        """Page 8 content (sec_b) is findable via the API."""
        r = requests.post(
            f"{api_server}/api/search",
            json=_granth_payload("प्रकाश की गति", exact_match=True),
        )
        assert r.status_code == 200
        data = r.json()
        assert data["granth_results"]["total_hits"] > 0

    def test_pravachan_search_returns_nothing(self, api_server):
        """With only Pravachan enabled, granth-categorised docs are never returned."""
        payload = {
            "query": "पानी हवा और धूप",
            "language": "hi",
            "exact_match": True,
            "exclude_words": [],
            "categories": {},
            "search_types": {
                "Pravachan": {"enabled": True,  "page_size": 10, "page_number": 1},
                "Granth":    {"enabled": False, "page_size": 10, "page_number": 1},
            },
            "enable_reranking": False,
        }
        r = requests.post(f"{api_server}/api/search", json=payload)
        assert r.status_code == 200
        data = r.json()
        assert data["pravachan_results"]["total_hits"] == 0

    def test_granth_vector_search_returns_results(self, api_server):
        """4-word query with exact_match=False routes to vector search; granth docs are returned."""
        # is_lexical_query returns False for 4+ words → vector path in search_api.py
        r = requests.post(
            f"{api_server}/api/search",
            json=_granth_payload("पानी हवा और धूप", exact_match=False),
        )
        assert r.status_code == 200
        data = r.json()
        assert data["granth_results"]["total_hits"] > 0